name: The Mindful Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.51648
title: the mindful way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#353533'
    - '#5d7594'
    - '#b8d8fe'
    - '#eae2bd'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
