name: The Mindful Way
favicon: null
layout_spectrum: 0.74282
typography_spectrum: 0.48511
title: the mindful way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#75aeff'
    - '#19181e'
    - '#3c57a2'
    - '#a39990'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
