name: The Mindful Way
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12694
title: the mindful way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#c5ad03'
    - '#4a9bbf'
    - '#8540ce'
    - '#5ce0ed'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
