typography_spectrum: 0.18107442138716578
color:
  brandColors:
    - '#ffffff'
    - '#75aeff'
    - '#19181e'
    - '#3c57a2'
    - '#a39990'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3107746865134686
analytics:
  google: null
  facebook: null
  twitter: null
name: The Mindful Way
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Courses in the Borders
    id: 995ee48a-fcd4-44a0-8947-c51ca106ce94
    type: content
  - name: Courses in Edinburgh
    id: e90043ba-d18d-4560-aead-262a48e8205d
    type: content
  - name: Core Process Psychotherapy
    id: bdd07803-6260-4046-bb18-9380adda8ece
    type: content
  - name: Mindfulness in Relationship
    id: 3827da7a-35fd-45f8-9a24-e100aef5cc9f
    type: content
  - name: Diploma Course
    id: be24927a-5528-4703-a07f-6e2d6652ee06
    type: content
  - name: Retreats
    id: 07c01f21-b03b-4f48-ad51-8ebb0736cc5f
    type: content
  - name: Testimonials
    id: ed29f4c1-ee65-48cc-8722-501cc6a062c7
    type: content
favicon: null
title: the mindful way
description: Discover the Power of Mindfulness
purpose: []
