typography_spectrum: 0.11054738657549024
color:
  brandColors:
    - '#ffffff'
    - '#75aeff'
    - '#19181e'
    - '#3c57a2'
    - '#a39990'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9008398074656725
analytics:
  google: null
  facebook: null
  twitter: null
name: The Mindful Way
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: What is Mindfulness?
    id: d71dd9de-df32-4ec4-a0d2-326b1a8ff422
    type: content
  - name: Courses in the Borders
    id: 995ee48a-fcd4-44a0-8947-c51ca106ce94
    type: content
  - name: Courses in Edinburgh
    id: e90043ba-d18d-4560-aead-262a48e8205d
    type: content
  - name: Mindfulness-based Psychotherapy
    id: bdd07803-6260-4046-bb18-9380adda8ece
    type: content
  - name: Relational Mindfulness Workshop
    id: 3827da7a-35fd-45f8-9a24-e100aef5cc9f
    type: content
  - name: Diploma Course
    id: be24927a-5528-4703-a07f-6e2d6652ee06
    type: content
  - name: Testimonials
    id: ed29f4c1-ee65-48cc-8722-501cc6a062c7
    type: content
  - name: In crisis?
    id: 6ca170ff-aa12-4b3f-a1ce-3c331869f3a7
    type: content
favicon: null
title: ''
description: ''
purpose: []
