name: The Mindful Way
favicon: null
layout_spectrum: 0.7124412371776998
typography_spectrum: 0.39360876358114183
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4599282806739211
  lightness: 0.13948571868240833
  saturation: 0.8570750621147454
  rhythmicContrast: 0.2958648377098143
purpose: []
