typography_spectrum: 0.18107442138716578
color:
  brandColors:
    - '#ffffff'
    - '#75aeff'
    - '#19181e'
    - '#3c57a2'
    - '#a39990'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3107746865134686
analytics:
  google: null
  facebook: null
  twitter: null
name: The Mindful Way
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Courses in the Borders
    id: 995ee48a-fcd4-44a0-8947-c51ca106ce94
    type: content
  - name: Courses in Edinburgh
    id: e90043ba-d18d-4560-aead-262a48e8205d
    type: content
  - name: Mindfulness in Relationship
    id: 8ecb43e4-3a5b-4783-b0e4-923300af976b
    type: content
favicon: null
title: the mindful way
purpose: []
