name: The Mindful Way
favicon: null
layout_spectrum: 0.90067
typography_spectrum: 0.40668
title: the mindful way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#99cbfe'
    - '#528dd5'
    - '#1d4e90'
    - '#213218'
  brandStrength: 0.4599282806739211
  lightness: 0.13948571868240833
  saturation: 0.8570750621147454
  rhythmicContrast: 0.2958648377098143
purpose: []
